before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - format: binary

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
  - repository:
      owner: assay-it
      name: assay-it
    folder: Formula
    goarm: "7"
    homepage:  https://assay.it
    description: Confirm Quality and Eliminate Risk by Testing Microservices in Production.
    license: MIT
    test: |
      system "#{bin}/assay-it -v"
    dependencies:
      - name: go
    # install: |-
    #   bin.install "assay-it"

# The lines beneath this are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
