# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AssayIt < Formula
  desc "Confirm Quality and Eliminate Risk by Testing Microservices in Production."
  homepage "https://assay.it"
  version "1.2.9"
  license "MIT"

  depends_on "go"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/assay-it/assay-it/releases/download/v1.2.9/assay-it_1.2.9_darwin_arm64"
      sha256 "b90de9372615ddfb7bf2ecff1305d4ae9cac1ae93a14a872a13a9a3e4ee00819"

      def install
        bin.install "assay-it_1.2.9_darwin_arm64" => "assay-it"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/assay-it/assay-it/releases/download/v1.2.9/assay-it_1.2.9_darwin_amd64"
      sha256 "0aab87fca2918d55ad547f4eacf9d1980f2426d87310daa492cb92de51e20573"

      def install
        bin.install "assay-it_1.2.9_darwin_amd64" => "assay-it"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/assay-it/assay-it/releases/download/v1.2.9/assay-it_1.2.9_linux_arm64"
      sha256 "1151fa9df5be9f8ed2f405108ae4dcf36619ad6d21cb7133918536f88e11c0a3"

      def install
        bin.install "assay-it_1.2.9_linux_arm64" => "assay-it"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/assay-it/assay-it/releases/download/v1.2.9/assay-it_1.2.9_linux_amd64"
      sha256 "0f7b863224c10e373ab5d2e1d27c75b472f8c716180752b75a79808dbcfa7367"

      def install
        bin.install "assay-it_1.2.9_linux_amd64" => "assay-it"
      end
    end
  end

  test do
    system "#{bin}/assay-it -v"
  end
end
