# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AssayIt < Formula
  desc "Confirm Quality and Eliminate Risk by Testing Microservices in Production."
  homepage "https://assay.it"
  version "1.2.8"
  license "MIT"

  depends_on "go"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/assay-it/assay-it/releases/download/v1.2.8/assay-it_1.2.8_darwin_amd64"
      sha256 "00cc290741384726e63f69493215451aab0285e856229d7b1e92cfb0996be9b3"

      def install
        bin.install "assay-it_1.2.8_darwin_amd64" => "assay-it"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/assay-it/assay-it/releases/download/v1.2.8/assay-it_1.2.8_darwin_arm64"
      sha256 "731b85d3bfa034e678f1aab680e39ba71ba8c07a4d9c86927081d2ce7438a00b"

      def install
        bin.install "assay-it_1.2.8_darwin_arm64" => "assay-it"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/assay-it/assay-it/releases/download/v1.2.8/assay-it_1.2.8_linux_arm64"
      sha256 "0fb3847ef072a44e3335dfd76250970e1748787092230679bd57510008bab719"

      def install
        bin.install "assay-it_1.2.8_linux_arm64" => "assay-it"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/assay-it/assay-it/releases/download/v1.2.8/assay-it_1.2.8_linux_amd64"
      sha256 "5fc745fdd6e26d5bafaeb02fd720ad423b71e80a5d11dde975392b6c5adc314c"

      def install
        bin.install "assay-it_1.2.8_linux_amd64" => "assay-it"
      end
    end
  end

  test do
    system "#{bin}/assay-it -v"
  end
end
