name: carry

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  carry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - uses: actions/checkout@v4.1.1
        with:
          ref: ${{ github.event.ref }}

      - uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          #version: ${{ github.event.ref }}
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}